### ISSUE TITLE
Execution broken with AppVeyor starting from codecov-exe v1.12.0

### ISSUE THREAD

**Issue by jgonzalezdr** [codecov/codecov-exe#146] opened 2020-11-06 08:33 UTC
With AppVeyor (at least, I don't know if with other CIs) the execution is broken, failing with the error "`codecov : [FTL] The system cannot find the file specified.`".

You can check a failing build log with [v1.12.0 here](https://ci.appveyor.com/project/jgonzalezdr/colorconsolelib/builds/36167385) and with [v1.12.3 here](https://ci.appveyor.com/project/jgonzalezdr/colorconsolelib/builds/36167048).

With exactly the same configuration, but running v1.11.2, it works properly (build log [here](https://ci.appveyor.com/project/jgonzalezdr/colorconsolelib/builds/36167337)).

**Comment by AdmiringWorm** [comment] 2020-11-10 13:25
hmm, could be a problem with how the VCS providers are resolved (it changed to use reflection in 1.12.0).

Could I ask you to try with the .NET Core edition of codecov-exe? (.NET Core is available on appveyor, and can be installed by running `dotnet tool install -g codecov.tool`).

My guess is that when publishing the .NET edition used in the chocolatey package, some required classes are removed since they are only used through reflection.

**Comment by AdmiringWorm** [comment] 2020-11-10 13:43
ignore my previous comment.
It seems the problem is something else, and I need to look a bit deeper into why it happens.
It looks like git somehow can not be found on the system, which is incorrect (even if it was, there should not be an exception :cry:).

**Comment by AdmiringWorm** [comment] 2021-02-15 23:25
A fix for this will be available in the next version of codecov-exe (I am sorry about the delay).

**Closed as completed by AdmiringWorm** 2021-02-15 23:25 UTC
Labels: Bug
