### ISSUE TITLE
Error when uploading report

### ISSUE THREAD

**Issue by KentonPickard** [codecov/codecov-exe#20] opened 2017-07-29 14:44 UTC
Am trying to get this setup...

I was able to generate the coverage report xml file but I'm running into issues trying to upload it with codecov.exe.  

I got different errors, and I am just seeing blank coverage data when I log into codedov.io.  It is a large project and the xml file is 137,000KB.  Any ideas?  Better error messages would also be appreciated.  

Here's what I tried and the results I got:

c:\Code\codecov-test>packages\Codecov.1.0.1\tools\codecov.exe -f ".\api_unit_tests.xml" -t <redacted>

              _____          _
             / ____|        | |
            | |     ___   __| | ___  ___ _____   __
            | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
            | |___| (_) | (_| |  __/ (_| (_) \ V /
             \_____\___/ \____|\___|\___\___/ \_/
                                         exe-1.0.1

2017-07-29 10:28:09 [Warning] No CI detected.
2017-07-29 10:28:09 [Information] Git detected.
2017-07-29 10:28:10 [Information] Project root: c:\Code\codecov-test
2017-07-29 10:28:10 [Information] Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
2017-07-29 10:28:10 [Information] Reading reports.
2017-07-29 10:28:10 [Information] .\_api_unit_tests.xml
2017-07-29 10:28:10 [Information] Uploading Reports.
2017-07-29 10:28:11 [Information] url: https://codecov.io
2017-07-29 10:28:12 [Information] query: https://codecov.io/upload/v4?branch=master&commit=9617e1f6f0c812caf081a9db88dd786092be31f8&build=&tag=&pr=&name=&flags=&slug=KentonPickard%2Ffd-enterprise-codecov&package=exe-1.0.1&build_url=&yaml=&job=&service=
2017-07-29 10:28:12 [Information] Pinging Codecov
2017-07-29 10:30:01 [Fatal] One or more errors occurred. (A task was canceled.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Codecov.Upload.Upload.Uploader() in C:\Users\Administrator\github\codecov-exe\Source\Codecov\Upload\Upload.cs:line 60
   at Codecov.Program.UploadFacade.Uploader() in C:\Users\Administrator\github\codecov-exe\Source\Codecov\Program\UploadFacade.cs:line 119
   at Codecov.Program.Run.Runner(IEnumerable`1 args) in C:\Users\Administrator\github\codecov-exe\Source\Codecov\Program\Run.cs:line 20

**On a 2nd Attempt:**

c:\Code\fd-enterprise-codecov>packages\Codecov.1.0.1\tools\codecov.exe -f ".\api_unit_tests.xml" -t <redacted>

              _____          _
             / ____|        | |
            | |     ___   __| | ___  ___ _____   __
            | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
            | |___| (_) | (_| |  __/ (_| (_) \ V /
             \_____\___/ \____|\___|\___\___/ \_/
                                         exe-1.0.1

2017-07-29 10:31:21 [Warning] No CI detected.
2017-07-29 10:31:22 [Information] Git detected.
2017-07-29 10:31:22 [Information] Project root: c:\Code\fd-enterprise-codecov
2017-07-29 10:31:22 [Information] Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
2017-07-29 10:31:22 [Information] Reading reports.
2017-07-29 10:31:22 [Information] .\api_unit_tests.xml
2017-07-29 10:31:22 [Information] Uploading Reports.
2017-07-29 10:31:23 [Information] url: https://codecov.io
2017-07-29 10:31:24 [Information] query: https://codecov.io/upload/v4?branch=master&commit=9617e1f6f0c812caf081a9db88dd786092be31f8&build=&tag=&pr=&name=&flags=&slug=KentonPickard%2Ffd-enterprise-codecov&package=exe-1.0.1&build_url=&yaml=&job=&service=
2017-07-29 10:31:24 [Information] Pinging Codecov
2017-07-29 10:31:50 [Fatal] One or more errors occurred. (The remote server returned an error: (403) Forbidden.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Codecov.Upload.Upload.Uploader() in C:\Users\Administrator\github\codecov-exe\Source\Codecov\Upload\Upload.cs:line 60
   at Codecov.Program.UploadFacade.Uploader() in C:\Users\Administrator\github\codecov-exe\Source\Codecov\Program\UploadFacade.cs:line 119
   at Codecov.Program.Run.Runner(IEnumerable`1 args) in C:\Users\Administrator\github\codecov-exe\Source\Codecov\Program\Run.cs:line 20

**Comment by larzw** [comment] 2017-07-29 15:15
Hi!

The query looks right. On the second attempt that looks like codecov's servers actually failed. What version of windows are you using (windows 10, windows 7,...)? Are you on a 32 bit or 64 bit machine? Can you post the coverage xml (or email it to me). I'll see if I can get it to upload. 
Thanks!

**Comment by larzw** [comment] 2017-07-29 15:20
Also, I noticed you issued the command
`c:\Code\codecov-test>packages\Codecov.1.0.1\tools\codecov.exe -f ".\api_unit_tests.xml" -t`
Did you include the value for your token? It will look something like...

`c:\Code\codecov-test>packages\Codecov.1.0.1\tools\codecov.exe -f ".\api_unit_tests.xml" -t 00000000-0000-0000-0000-000000000000.`

you get the token from codecov's website.

Thanks!

**Comment by larzw** [comment] 2017-07-30 01:13
@KentonPickard,

Thanks again for reporting this. I agreed the error reporting is not the best. I believe the issue is with the token. I don't see a token in the query string (from your above output). For example, you should see something like...

```
2017-07-29 10:31:24 [Information] query: https://codecov.io/upload/v4?branch=master&commit=9617e1f6f0c812caf081a9db88dd786092be31f8&build=&tag=&pr=&name=&flags=&slug=KentonPickard%2Ffd-enterprise-codecov&package=exe-1.0.1&token=&build_url=&yaml=&job=&service=
``` 
Where I added `token=` to the query string. For security, the value of the token is removed from the logging. But if you run in verbose mode `-v` you'll see the value. Furthermore, if the token is not in the correct format (it has to be a guid!) then it's value will default to empty string. FYI, if your running this on appveyor you don't need to specify a token.

Thanks and let me know if this fixes the issue.

**Comment by KentonPickard** [comment] 2017-07-30 01:27
Hey @larzw.  Thanks for looking into this so quickly!  I have sent you a message to your gmail account with more details including the xml coverage report and the exact commands I executed.  

I did specify a token when calling codecov.exe via the -t parameter but did not include it in my post as I think its supposed to be private info.  

Please let me know if you don't get the e-mail.    Thanks!

**Comment by larzw** [comment] 2017-08-07 17:05
@KentonPickard, this is fixed now. I should get a release out in the next few days. If you are having anymore issues with this uploader let me know! If you are having any issues with getting the report to process on codecov's infrastructure (since it's such a large file) I would recommend contacting the codecov team.

**Closed as completed by larzw** 2017-08-07 17:05 UTC
Labels: Bug
